call genPyCli.bat  %ROS_HOME%\lib\controller_manager\controller_group
call genPyCli.bat  %ROS_HOME%lib\controller_manager\controller_manager
call genPyCli.bat  %ROS_HOME%lib\controller_manager\spqwner
call genPyCli.bat  %ROS_HOME%lib\controller_manager\unspawner
call genPyCli.bat  %ROS_HOME%lib\joint_state_publisher\joint_state_publisher
call genPyCli.bat  %ROS_HOME%lib\moveit_ros_move_group\load_map
call genPyCli.bat  %ROS_HOME%lib\moveit_ros_move_group\save_map
call genPyCli.bat  %ROS_HOME%lib\rqt_controller_manager\rqt_controller_manager
call genPyCli.bat  %ROS_HOME%lib\rqt_joint_trajectory_controller\rqt_joint_trajectory_controller
call genPyCli.bat  %ROS_HOME%lib\rqt_moveit\rqt_moveit
