#!/usr/bin/env python3
#
from __future__ import print_function
import os.path
import sys
import xml.dom.minidom

def get_pkg_name(pth):
  fname=pth+"/package.xml"
  pkg_dom=dom=xml.dom.minidom.parse(fname)
  name = pkg_dom.getElementsByTagName('name')
  try:
    return name[0].childNodes[0].data
  except:
    return pth

if __name__ == '__main__':
  print(get_pkg_name(sys.argv[1]))
